[build]
  command = "echo 'Netlify build complete'"
  publish = "."

[[redirects]]
  from = "/.netlify/functions/get-achievements"
  to = "/.netlify/functions/get-achievements"
  status = 200
